Repository WildCodeSchool/purple-php-2109-project3-powy, pull requests merged in 2022-01, with the labels that each got.

#14 Front etudiant
  assets/app.js
  assets/images/chevron.png
  assets/images/num1.png
  assets/images/num2.png
  assets/images/num3.png
  assets/images/num4.png
  assets/js/index.js
  assets/styles/app.scss
  assets/styles/rgpd.scss
  assets/styles/student.scss
  src/Controller/StudentController.php
  templates/home/index.html.twig
  templates/login/index.html.twig
  templates/student/index.html.twig
Labels: reviewed, corrections done

#21 Us1 studententity
  migrations/Version20220102125048.php
  migrations/Version20220102131920.php
  src/DataFixtures/StudentFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/ProfessionalSector.php
  src/Entity/Student.php
  src/Entity/User.php
  src/Repository/StudentRepository.php
Labels: reviewed

#23 Us35 mentorinformations
  assets/styles/app.scss
  assets/styles/mentor.scss
  src/Controller/MentorController.php
  templates/base.html.twig
  templates/home/index.html.twig
  templates/mentor/index.html.twig
Labels: reviewed

#20 add functionality view profil information
  assets/images/phone.png
  assets/images/sendemail.png
  assets/styles/app.scss
  assets/styles/profile.scss
  src/Controller/ProfileController.php
  templates/components/_header.html.twig
  templates/login/index.html.twig
  templates/profile/index.html.twig
Labels: reviewed

#24 fix nullable entity user and student
  migrations/Version20220104152433.php
  src/Entity/Student.php
  src/Entity/User.php
Labels: reviewed

#22 Us9/modification information
  assets/styles/profile.scss
  src/Controller/ProfileController.php
  src/Form/EditPasswordType.php
  src/Form/EditProfileType.php
  templates/profile/edit.html.twig
  templates/profile/index.html.twig
Labels: reviewed, corrections done

#27 FAQ client textes added
  templates/components/_faq.html.twig
Labels: reviewed

#29 Us2 - mentor & company entities
  migrations/Version20220105144057.php
  src/Entity/Company.php
  src/Entity/Mentor.php
  src/Entity/ProfessionalSector.php
  src/Entity/User.php
  src/Repository/CompanyRepository.php
  src/Repository/MentorRepository.php
Labels: reviewed

#28 Fix footer
  assets/styles/connexion.scss
  assets/styles/footer.scss
  assets/styles/header.scss
  templates/base.html.twig
  templates/components/_footer.html.twig
  templates/components/_header.html.twig
  templates/home/index.html.twig
  templates/login/index.html.twig
  templates/mentor/index.html.twig
  templates/profile/index.html.twig
  templates/rgpd/index.html.twig
  templates/student/index.html.twig
Labels: reviewed

#30 changed font
  assets/fonts/Montserrat-Light.ttf
  assets/fonts/Roboto-Bold.ttf
  assets/fonts/Roboto-Regular.ttf
  assets/styles/variables.scss
Labels: reviewed

#31 Us9/modification information front
  assets/images/upload-icon.png
  assets/styles/app.scss
  assets/styles/body.scss
  assets/styles/profile-edit.scss
  assets/styles/profile.scss
  src/Form/EditPasswordType.php
  src/Form/EditProfileType.php
  templates/profile/edit.html.twig
Labels: reviewed

#32 added component faq
  templates/home/index.html.twig
  templates/mentor/index.html.twig
  templates/student/index.html.twig
Labels: reviewed

#25 make-register-form
  composer.json
  composer.lock
  config/bundles.php
  migrations/Version20220104134712.php
  migrations/Version20220106095426.php
  src/Controller/RegistrationController.php
  src/DataFixtures/StudentFixtures.php
  src/Entity/ProfessionalSector.php
  src/Entity/School.php
  src/Entity/Student.php
  src/Entity/StudyLevel.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  src/Form/StudentType.php
  src/Security/EmailVerifier.php
  symfony.lock
  templates/components/_flashmessages.html.twig
  templates/home/index.html.twig
  templates/login/index.html.twig
  templates/mentor/index.html.twig
  templates/profile/index.html.twig
  templates/registration/confirmation_email.html.twig
  templates/registration/register.html.twig
  templates/student/index.html.twig
Labels: reviewed, corrections done

#38 redirect user to profile after login
  templates/login/index.html.twig
Labels: reviewed

#39 security route /profile
  src/Controller/ProfileController.php
Labels: reviewed

#40 fixed flash messages when registration
  src/Controller/RegistrationController.php
  templates/login/index.html.twig
Labels: reviewed

#41 fix people background and padding presentation
  assets/images/groupe-personne.png
  assets/styles/home.scss
Labels: reviewed

#37 added a regex on plainpassword
  src/DataFixtures/UserFixtures.php
  src/Form/RegistrationFormType.php
  templates/registration/register.html.twig
Labels: reviewed, corrections done

#33 unsuscribe method
  src/Controller/ProfileController.php
  templates/profile/_delete_form.html.twig
  templates/profile/index.html.twig
Labels: reviewed, corrections done

#43 fix redirect register and login if the user is connected
  src/Controller/LoginController.php
  src/Controller/RegistrationController.php
Labels: reviewed, corrections done

#47 Fix assert age
  config/packages/translation.yaml
  src/Entity/User.php
Labels: reviewed

#42 upload picture and fix edit user
  assets/styles/body.scss
  assets/styles/profile-edit.scss
  assets/styles/profile.scss
  config/services.yaml
  migrations/Version20220114082314.php
  public/upload/pictures/user.png
  src/Controller/ProfileController.php
  src/Entity/User.php
  src/Form/EditProfileType.php
  src/Service/FileUploader.php
  templates/profile/edit.html.twig
  templates/profile/index.html.twig
Labels: reviewed, corrections done

#45 fix css
  assets/images/logo.png
  assets/styles/body.scss
  assets/styles/connexion.scss
  assets/styles/header.scss
  assets/styles/home.scss
  assets/styles/profile-edit.scss
  assets/styles/profile.scss
  templates/components/_header.html.twig
  templates/profile/index.html.twig
Labels: reviewed

#50 Us50 match service
  migrations/Version20220114091434.php
  src/DataFixtures/MentorFixtures.php
  src/DataFixtures/StudentFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Mentor.php
  src/Entity/Mentoring.php
  src/Entity/Student.php
  src/Repository/MentoringRepository.php
  src/Service/MatchManager.php
Labels: reviewed

#52 updated readme (setup up smtp)
  README.md
Labels: reviewed

#57 fix css picture
  assets/styles/profile.scss
Labels: reviewed

#53 Fix password etc
  .gitignore
  src/Controller/ProfileController.php
  src/DataFixtures/UserFixtures.php
  src/Form/MentorType.php
  src/Form/StudentType.php
Labels: reviewed

#54 Us36 password reset
  src/Controller/LoginController.php
  src/Controller/RegistrationController.php
  src/DataFixtures/UserFixtures.php
  src/Form/EditPasswordType.php
  src/Form/EmailFormType.php
  src/Security/EmailVerifier.php
  templates/login/changePasswordEmail.html.twig
  templates/login/change_password.html.twig
  templates/login/index.html.twig
  templates/login/reset.html.twig
  templates/profile/password_changed.html.twig
Labels: reviewed, corrections done

#56 student register form css
  assets/images/logo-powy.png
  assets/styles/app.scss
  assets/styles/student-register-form.scss
  templates/registration/register_mentor.html.twig
  templates/registration/register_student.html.twig
Labels: reviewed, corrections done

#58 Us17 - entity Topic creation & match by topic
  migrations/Version20220118132844.php
  src/DataFixtures/MentorFixtures.php
  src/DataFixtures/StudentFixtures.php
  src/DataFixtures/TopicFixtures.php
  src/Entity/Mentor.php
  src/Entity/Student.php
  src/Entity/Topic.php
  src/Form/MentorType.php
  src/Form/StudentType.php
  src/Form/TopicType.php
  src/Repository/MentorRepository.php
  src/Repository/TopicRepository.php
  src/Service/MatchManager.php
  templates/registration/register_mentor.html.twig
  templates/registration/register_student.html.twig
Labels: reviewed, corrections done

#59 finally fix the footer with grid
  assets/styles/body.scss
  assets/styles/footer.scss
Labels: reviewed

#60 put all the emails template in emails directory
  src/Controller/LoginController.php
  src/Controller/RegistrationController.php
  templates/emails/changePasswordEmail.html.twig
  templates/emails/confirmation_email.html.twig
  templates/emails/password_changed.html.twig
  templates/emails/registration_email.html.twig
Labels: reviewed

#63 card effect on studylevel, changed fixtures
  assets/styles/student-register-form.scss
  assets/styles/variables.scss
  src/DataFixtures/StudyLevelFixtures.php
  src/Form/StudentType.php
  templates/registration/register_student.html.twig
Labels: reviewed

#64 Us42 form js next
  assets/app.js
  assets/js/form.js
  assets/styles/student-register-form.scss
  templates/registration/register_student.html.twig
Labels: reviewed

#65 mentor front form
  assets/styles/app.scss
  assets/styles/mentor-register-form.scss
  templates/registration/register_mentor.html.twig
Labels: reviewed, corrections done

#66 added cards effect on scholarship checkbox
  assets/styles/student-register-form.scss
  src/Form/StudentType.php
  templates/registration/register_student.html.twig
Labels: reviewed

#67 fix header
  assets/styles/body.scss
  assets/styles/header.scss
  assets/styles/student-register-form.scss
  templates/components/_header.html.twig
Labels: reviewed

#68 Display form mentor
  assets/js/form.js
  assets/styles/mentor-register-form.scss
  templates/registration/register_mentor.html.twig
Labels: reviewed

#69 CGU page
  assets/styles/app.scss
  assets/styles/cgu.scss
  src/Controller/CguController.php
  templates/cgu/index.html.twig
  templates/components/_footer.html.twig
Labels: reviewed

#72 added an input with JS and CSS if selected school is 'other'
  assets/js/form.js
  assets/styles/student-register-form.scss
  src/Controller/RegistrationController.php
  src/DataFixtures/CompanyFixtures.php
  src/DataFixtures/SchoolFixtures.php
  src/Form/MentorType.php
  src/Form/StudentType.php
  templates/registration/register_mentor.html.twig
  templates/registration/register_student.html.twig
Labels: reviewed

#74 Fix display profile
  assets/styles/footer.scss
  assets/styles/profile.scss
  templates/profile/index.html.twig
Labels: reviewed

#75 added a button to refresh the chat page
  assets/styles/chat.scss
  templates/chat/index.html.twig
Labels: reviewed

#77 fix register bug
  assets/js/form.js
  assets/styles/student-register-form.scss
  src/Controller/RegistrationController.php
  src/Form/MentorType.php
  src/Form/StudentType.php
  templates/registration/register_mentor.html.twig
  templates/registration/register_student.html.twig
Labels: reviewed 2

#76 Us16/mentorat mail
  .gitignore
  migrations/Version20220126134433.php
  src/Controller/MentorController.php
  src/Controller/MentoringController.php
  src/Controller/RegistrationController.php
  src/Entity/Mentoring.php
  src/Service/MailerManager.php
  src/Service/MatchManager.php
  src/Service/MentoringManager.php
  templates/emails/mentoring_confirmation.html.twig
  templates/emails/mentoring_proposal.html.twig
  templates/student/confirmation_email_mentorat.html.twig
  templates/student/demande_email.html.twig
Labels: reviewed 1

#79 fix, match is ok is mentor has not the same sector pro
  src/Service/MatchManager.php
Labels: reviewed 1

#83 add tooltip in form
  assets/js/form.js
  assets/styles/student-register-form.scss
  templates/registration/register_mentor.html.twig
  templates/registration/register_student.html.twig
Labels: reviewed 2

#80 Fix 5 et fix 14
  src/Controller/ChatController.php
  src/Controller/ProfileController.php
  src/DataFixtures/MentoringFixtures.php
  src/Service/MentoringManager.php
  templates/profile/index.html.twig
Labels: reviewed 2

#82 Methods removeMessage and updated stopMentoring
  src/Service/MentoringManager.php
Labels: corrections done, reviewed 2, Merge in first pls

#81 Admin Dashboard & Find Mentoring & User edit show delete
  .gitignore
  assets/images/edit.png
  assets/styles/admin.scss
  assets/styles/app.scss
  config/packages/security.yaml
  src/Controller/Admin/AdminController.php
  src/Controller/Admin/MentoringController.php
  src/Controller/Admin/UserController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Mentor.php
  src/Form/UserType.php
  templates/admin/components/_navbar.html.twig
  templates/admin/index.html.twig
  templates/admin/mentoring/_delete_form.html.twig
  templates/admin/mentoring/index.html.twig
  templates/admin/user/_delete_form.html.twig
  templates/admin/user/edit.html.twig
  templates/admin/user/index.html.twig
  templates/profile/index.html.twig
Labels: corrections done, reviewed 2

#85 Fix 16 - fixed error message when no match is found
  src/Repository/MentorRepository.php
  src/Service/MatchManager.php
Labels: reviewed 2

#86 mentoring disable
  src/Controller/Admin/MentoringController.php
  templates/admin/mentoring/index.html.twig
Labels: reviewed 2

#87 Us52 - match and end an expired mentoring at each connexion
  src/Controller/LoginController.php
  src/DataFixtures/MentoringFixtures.php
  src/Service/MatchManager.php
  src/Service/MentoringManager.php
Labels: reviewed 2

#90 changed display of mentoring
  assets/styles/profile.scss
  templates/profile/index.html.twig
Labels: reviewed 2

#97 Remove the match method in edit choices of the profile controller
  src/Controller/ProfileController.php
Labels: reviewed 2

#98 fix info mentor css
  assets/styles/app.scss
  assets/styles/mentor.scss
  templates/mentor/index.html.twig
Labels: reviewed 2

#99 Us47 Topic in DB
  migrations/Version20220127164802.php
  src/DataFixtures/MentoringFixtures.php
  src/Entity/Mentoring.php
  src/Service/MatchManager.php
Labels: reviewed 2

#100 changed style on topics choices
  assets/styles/profile-edit.scss
  assets/styles/student-register-form.scss
  src/Entity/Topic.php
  templates/profile/choices.html.twig
  templates/registration/register_mentor.html.twig
  templates/registration/register_student.html.twig
Labels: reviewed 2

#101 Fix20
  src/Service/MailerManager.php
  templates/emails/changePasswordEmail.html.twig
  templates/emails/confirmation_email.html.twig
  templates/emails/mentoring_confirmation.html.twig
  templates/emails/mentoring_proposal.html.twig
  templates/emails/password_changed.html.twig
  templates/emails/registration_email.html.twig
Labels: reviewed 1

#95 list user unverified administration
  assets/images/trash.png
  migrations/Version20220128100009.php
  src/Controller/Admin/UserController.php
  src/Controller/RegistrationController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Repository/UserRepository.php
  templates/admin/components/_navbar.html.twig
  templates/admin/index.html.twig
  templates/admin/mentoring/index.html.twig
  templates/admin/user/_delete_form.html.twig
  templates/admin/user/list/index.html.twig
Labels: reviewed 2

#102 fixed error message offset
  src/Service/MatchManager.php
Labels: reviewed 2

#103 fix date
  src/Controller/RegistrationController.php
Labels: reviewed 1
