Repository WildCodeSchool/purple-php-2109-project3-powy, pull requests merged in 2022-02, with the labels that each got.

#106 fixed security on chat controller
  src/Controller/ChatController.php
Labels: reviewed 1, To review

#107 Fix21 27 28
  src/Form/EditProfileType.php
  src/Form/MentorType.php
  src/Form/RegistrationFormType.php
  src/Form/StudentType.php
  templates/profile/edit.html.twig
Labels: reviewed

#110 Fix init bdd
  assets/images/favicon.png
  migrations/Version20220131185053.php
  src/Entity/ProfessionalSector.php
Labels: reviewed

#111 added CGU, chart and RGPD link
  assets/js/index.js
  assets/styles/mentor-register-form.scss
  assets/styles/student-register-form.scss
  src/Form/MentorType.php
  src/Form/RegistrationFormType.php
  templates/registration/register_mentor.html.twig
  templates/registration/register_student.html.twig
Labels: reviewed

#113 Fix9 11 38 40
  assets/styles/body.scss
  assets/styles/footer.scss
  assets/styles/profile-edit.scss
  assets/styles/student-register-form.scss
  src/Controller/ProfileController.php
  src/Service/MailerManager.php
  templates/components/_faq.html.twig
  templates/emails/delete_account_email.html.twig
  templates/login/change_password.html.twig
  templates/login/reset.html.twig
  templates/mentor/index.html.twig
  templates/profile/choices.html.twig
  templates/profile/edit.html.twig
  templates/registration/register_mentor.html.twig
  templates/registration/register_student.html.twig
  templates/student/confirmation_email_mentorat.html.twig
  templates/student/demande_email.html.twig
  templates/student/index.html.twig
Labels: reviewed

#112 FIX 31 button profile
  assets/styles/student-register-form.scss
  templates/registration/register_mentor.html.twig
  templates/registration/register_student.html.twig
Labels: reviewed, corrections done

#115 Fix18 add input
  src/Controller/RegistrationController.php
  src/Service/NewSchoolCompany.php
Labels: reviewed

#116 Fix29 36
  assets/js/index.js
  assets/styles/cgu.scss
  assets/styles/header.scss
  assets/styles/home.scss
  assets/styles/rgpd.scss
  templates/chat/index.html.twig
  templates/components/_footer.html.twig
  templates/components/_header.html.twig
  templates/home/index.html.twig
  templates/login/index.html.twig
  templates/mentor/index.html.twig
  templates/profile/choices.html.twig
  templates/profile/edit.html.twig
  templates/profile/index.html.twig
  templates/student/index.html.twig
Labels: reviewed, reviewed 2

#117 admin in database
  migrations/Version20220207151908.php
Labels: reviewed

#114 Fix30
  assets/styles/mentor-register-form.scss
  assets/styles/profile-edit.scss
  templates/profile/choices.html.twig
  templates/registration/register_mentor.html.twig
  templates/registration/register_student.html.twig
Labels: reviewed, reviewed 2

#118 Fix39 admin button
  assets/styles/admin.scss
  templates/profile/index.html.twig
Labels: reviewed

#108 fix user null
  .gitignore
  src/Repository/UserRepository.php
  templates/admin/components/_navbar.html.twig
  templates/admin/mentoring/index.html.twig
Labels: reviewed

#121 w3c validator profile
  templates/profile/choices.html.twig
  templates/profile/edit.html.twig
Labels: reviewed

#122 Fix38 - changed entity Mentoring to allow multiples mentorings
  migrations/Version20220131155132.php
  src/Controller/LoginController.php
  src/Controller/MentoringController.php
  src/Controller/ProfileController.php
  src/Controller/RegistrationController.php
  src/DataFixtures/MentoringFixtures.php
  src/Entity/Mentor.php
  src/Entity/Mentoring.php
  src/Entity/Student.php
  src/Entity/Topic.php
  src/Repository/MentorRepository.php
  src/Service/MailerManager.php
  src/Service/MatchManager.php
  src/Service/MentoringManager.php
  templates/emails/mentoring_proposal.html.twig
Labels: reviewed, reviewed 2

#123 Final Master for the team
  .gitignore
  assets/images/favicon.png
  assets/styles/admin.scss
  assets/styles/body.scss
  assets/styles/cgu.scss
  assets/styles/footer.scss
  assets/styles/header.scss
  assets/styles/home.scss
  assets/styles/mentor-register-form.scss
  assets/styles/profile-edit.scss
  assets/styles/rgpd.scss
  assets/styles/student-register-form.scss
  migrations/Version20220131155132.php
  migrations/Version20220131185053.php
  migrations/Version20220207151908.php
  src/Controller/ChatController.php
  src/Controller/LoginController.php
  src/Controller/MentoringController.php
  src/Controller/ProfileController.php
  src/Controller/RegistrationController.php
  src/DataFixtures/MentoringFixtures.php
  src/Entity/Mentor.php
  src/Entity/Mentoring.php
  src/Entity/ProfessionalSector.php
  src/Entity/Student.php
  src/Entity/Topic.php
  src/Form/EditProfileType.php
  src/Form/MentorType.php
  src/Form/RegistrationFormType.php
  src/Form/StudentType.php
  src/Form/TopicType.php
  src/Repository/MentorRepository.php
  src/Repository/UserRepository.php
  src/Service/MailerManager.php
  src/Service/MatchManager.php
  src/Service/MentoringManager.php
  src/Service/NewSchoolCompany.php
  templates/admin/components/_navbar.html.twig
  templates/admin/mentoring/index.html.twig
  templates/chat/index.html.twig
  templates/components/_faq.html.twig
  templates/components/_footer.html.twig
  templates/components/_header.html.twig
  templates/emails/delete_account_email.html.twig
  templates/emails/mentoring_proposal.html.twig
  templates/home/index.html.twig
  templates/login/change_password.html.twig
  templates/login/index.html.twig
  templates/login/reset.html.twig
  templates/mentor/index.html.twig
  templates/profile/choices.html.twig
  templates/profile/edit.html.twig
  templates/profile/index.html.twig
  templates/registration/register_mentor.html.twig
  templates/registration/register_student.html.twig
  templates/student/confirmation_email_mentorat.html.twig
  templates/student/demande_email.html.twig
  templates/student/index.html.twig
Labels: reviewed, reviewed 2
